# Site settings
name: 延卫
email: wangdaowei@hust.edu.cn
author: dovey
url: 
resume_site: https://wangdaowei.github.io/
github: https://github.com/wangdaowei/
baseurl: ""
description: 点滴积累，贵在坚持！
meta_description: 王道威;个人博客;
motto: keep running.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: wangdaowei

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

